name: Run code checks with different build tools

on:
  - push
  - pull_request

jobs:

  poetry:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check:
          - poetry check
          - poetry build

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Run check "${{ matrix.check }}"
        run: "${{ matrix.check }}"

  nix-flake:
    runs-on: ubuntu-latest

    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v22

    - uses: actions/checkout@v4

    - name: Build the nix derivation (also runs the tests)
      run: nix build --print-build-logs
